#!/bin/sh
set -e

if [ -z $1 ];
then
    echo "ERROR: Role not provided"
    exit 1
fi

echo "Assuming role: $1"
CREDS=`aws sts assume-role --role-arn $1 --role-session-name=${DRONE_REPO_OWNER}-${DRONE_REPO_NAME}`

AWS_ACCESS_KEY_ID=`echo $CREDS | jq -r '.Credentials.AccessKeyId'`
AWS_SECRET_ACCESS_KEY=`echo $CREDS | jq -r '.Credentials.SecretAccessKey'`
AWS_SESSION_TOKEN=`echo $CREDS | jq -r '.Credentials.SessionToken'`

echo "export AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}" >> $2
echo "export AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}" >> $2
echo "export AWS_SESSION_TOKEN=${AWS_SESSION_TOKEN}" >> $2
