#!/bin/bash
set -eux

wrap() {
  if [[ $(echo "$1" | wc -l) -gt 20 ]]; then
    echo "
<details><summary>Show Output</summary>
\`\`\`diff
$1
\`\`\`
</details>
"
else
    echo "
\`\`\`diff
$1
\`\`\`
"
fi
}

# Build the comment we'll post to the PR.
# Format the comment

OUTPUT=$1

# Remove "Refreshing state..." lines by only keeping output after the
# delimiter (72 dashes) that represents the end of the refresh stage.
# We do this to keep the comment output smaller.
if echo "$OUTPUT" | egrep '^-{72}$'; then
    OUTPUT=$(echo "$OUTPUT" | sed -n -r '/-{72}/,/-{72}/{ /-{72}/d; p }')
fi

# Remove whitespace at the beginning of the line for added/modified/deleted
# resources so the diff markdown formatting highlights those lines.
OUTPUT=$(echo "$OUTPUT" | sed -r -e 's/^  \+/\+/g' | sed -r -e 's/^  ~/~/g' | sed -r -e 's/^  -/-/g')

# Call wrap to optionally wrap our output in a collapsible markdown section.
OUTPUT=$(wrap "$OUTPUT")

COMMENT="####  terraform plan  Success \n $OUTPUT"


# Post the comment.
PAYLOAD=$(echo '{}' | jq --arg body "$COMMENT" '.body = $body')
COMMENTS_URL="https://api.github.com/repos/$DRONE_REPO/pulls/$CI_PULL_REQUEST/comments",

curl -v -k -f -H "Authorization: token $GITHUB_TOKEN" --header "Content-Type: application/json" --data "$PAYLOAD" "$COMMENTS_URL" > /dev/null 