#!/bin/bash

while getopts ":t:" opt; do
  case ${opt} in
    t )
      target=$OPTARG
      ;;
    \? )
      echo "Invalid option: $OPTARG" 1>&2
      ;;
    : )
      echo "Invalid option: $OPTARG requires an argument" 1>&2
      ;;
  esac
done
shift $((OPTIND -1))

# Variables needed:
TOKEN={$GITHUB_TOKEN}
PAYLOAD=$(echo '{}' | jq --arg body "$COMMENT" '.body = $body')
API_URL="https://api.github.com"/repos/$DRONE_REPO/statuses/$CI_COMMIT
STATE="error, failure, pending, or success."
DESCRIPTION=""
CONTEXT="ci/drone"

#notify terraform plan
curl -s -S -H "Authorization: token $GITHUB_TOKEN"  --header "Content-Type: application/json" --data "$PAYLOAD" "$API_URL" > /dev/null

#notify ci start
curl -k -f -H "Authorization: token $AUTH_TOKEN" --request POST --data "{\"state\": \"$BUILD_STATE\", \"description\": \"$BUILD_DESCRIPTION\", \"target_url\": \"$URL\", \"context\": \"$CONTEXT\"}" $GITHUB_STATUS_ENDPOINT

#notify ci result
curl -v -k -f -H "Authorization: token $AUTH_TOKEN" --request POST --data "{\"state\": \"pending\", \"description\": \"$PENDING_DESCRIPTION\", \"target_url\": \"$URL\", \"context\": \"$CONTEXT\"}" $GITHUB_STATUS_ENDPOINT
