#!/bin/bash

GITHUB_STATUS_ENDPOINT="https://api.github.com"/repos/$DRONE_REPO/statuses/$CI_COMMIT
PENDING_DESCRIPTION="The Bamboo CI build is in progress"
CONTEXT='C'

curl -v -k -f -H "Authorization: token $AUTH_TOKEN" --request POST \
--data "{\"state\": \"pending\", \"description\": \"$PENDING_DESCRIPTION\", \"target_url\": \"$CI_BUILD_URL\", \"context\": \"$CONTEXT\"}" $GITHUB_STATUS_ENDPOINT

exit_status=$?

if [ $exit_status != 0 ]
  then
    echo "github curl call failed: $exit_status"
    exit $exit_status
fi
